### ISSUE TITLE
There is a problem

### ISSUE THREAD

**Issue by bulentala** [topheman/nextjs-movie-browser#11]
![Ekran Resmi 2020-01-07 04 01 22](https://user-images.githubusercontent.com/46373855/71860081-84724b80-3102-11ea-99bc-ee60468d2891.png)

**Comment by topheman** [comment]
I just tried from a fresh git clone with:

MacOS 10.14.4
node: 10.15.3
yarn: 1.13.0
npm: 6.4.1

I tried both `yarn` and `npm install`, it works fine on both.

What version of node / yarn do you use ? Which OS do you use ?

**Comment by bulentala** [comment]
MacOs Catalina 10.15
Node : v12.13.1
Yarn : 1.13.0
Npm : 6.12.1

**Comment by topheman** [comment]
1) At the root of your project folder, run the following command :

```
cat node_modules/next/package.json|grep version
```

If you installed with yarn, it should return :

```
  "version": "8.0.3",
```

2) If it doesn't return that, uninstall and reinstall the node_modules :

```shell
rm -rf ./node_modules
yarn
```

If it still doesn't work, the problem might be from the node version (or OS system ?), if you use something like nvm and can easily try with node v10, it would be great, I can't make this test right now.

**Comment by bulentala** [comment]
I'll tray it... thanks...
